# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7700b52c74bcfae021795e27656ca3b418da06c4a95b561e1d0faad70ff9769c97e3bc0176ef42fed284e7b32d30706f33060cffb633b92285dc48ab246aaf3f

test:
  secret_key_base: e427a3b2ceeb46a83480c09eb0a8697df9befb4808b598f915b696272fad88b5219e1f1d76cf6a71b56d0d659e7765904bdc2fa043aac5de8ceea509eb14fde7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
